description: findOneAndUpdate-serverErrors

schemaVersion: '1.3'

runOnRequirements:
  -
    minServerVersion: '4.0'
    topologies: [ replicaset ]
  -
    minServerVersion: 4.1.7
    topologies: [ sharded, load-balanced ]

createEntities:
  -
    client:
      id: &client0 client0
      useMultipleMongoses: false
  -
    database:
      id: &database0 database0
      client: *client0
      databaseName: &database_name retryable-writes-tests
  -
    collection:
      id: &collection0 collection0
      database: *database0
      collectionName: &collection_name coll

initialData:
  -
    collectionName: *collection_name
    databaseName: *database_name
    documents:
      - { _id: 1, x: 11 }
      - { _id: 2, x: 22 }

tests:
  -
    description: 'FindOneAndUpdate fails with a RetryableWriteError label after two connection failures'
    operations:
      -
        name: failPoint
        object: testRunner
        arguments:
          client: *client0
          failPoint:
            configureFailPoint: failCommand
            mode: { times: 2 }
            data:
              failCommands: [ findAndModify ]
              closeConnection: true
      -
        object: *collection0
        name: findOneAndUpdate
        arguments:
          filter: { _id: 1 }
          update: { $inc: { x: 1 } }
          returnDocument: Before
        expectError:
          isError: true
          errorLabelsContain:
            - RetryableWriteError
    outcome:
      -
        collectionName: *collection_name
        databaseName: *database_name
        documents:
          - { _id: 1, x: 11 }
          - { _id: 2, x: 22 }
